### ISSUE TITLE
Cloud erroneously reports VPN connection down

### ISSUE THREAD

**Issue by kb2ma** [balena-io/open-balena-vpn#290]
**Describe the bug**
A device may remain in HeartbeatOnly status, but really has a VPN connection with with open-balena-vpn [1]. Look for this sequence of messages in the server VPN logs for the device:

1. Connected to worker X.1
1. Connected to pod Y
1. Quickly disconnected from pod Y
1. Connected to worker X.1 again

There is a silent disconnect from worker X.1 between item 1 and item 4. There likely is a race condition where the disconnect and connect that worker came in the wrong order.

This pattern is distinct from a related sequence where the server logs showed a "dropping oos disconnect" event. See #287 .

[1] At time of writing we have not *confirmed* that the device really has a VPN connection, but it seems likely.

**To Reproduce**
Verify that the device is connected to the VPN if possible.

**Logs / Screenshots**
A number in parentheses at the beginning of a line corresponds to the position in the sequence listed above.

```
17 Aug 2022 12:16:38.893open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=true
17 Aug 2022 12:16:39.038open-balena-vpn-5cf5d597b-djxcq vpn[716]: info: [vpn-127199.1] connection established with client_id=1701769 uuid=3d48dc2ce7eab29b063e38667417afce
17 Aug 2022 12:16:40.942open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=false
(1) 17 Aug 2022 12:16:56.937open-balena-vpn-5cf5d597b-74wz5 vpn[714]: info: [vpn-127211.1] connection established with client_id=1555092 uuid=3d48dc2ce7eab29b063e38667417afce
17 Aug 2022 12:16:57.182open-balena-vpn-5cf5d597b-74wz5 vpn[549]: debug: [vpn-127211] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=true
17 Aug 2022 12:38:49.398open-balena-vpn-5cf5d597b-djxcq vpn[716]: info: [vpn-127199.1] connection established with client_id=1724529 uuid=3d48dc2ce7eab29b063e38667417afce
(2) 17 Aug 2022 12:38:50.022open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=true
(3) 17 Aug 2022 12:38:54.141open-balena-vpn-5cf5d597b-djxcq vpn[551]: debug: [vpn-127199] successfully updated state for device: uuid=3d48dc2ce7eab29b063e38667417afce connected=false
(4) 17 Aug 2022 12:39:08.755open-balena-vpn-5cf5d597b-74wz5 vpn[714]: info: [vpn-127211.1] connection established with client_id=1577933 uuid=3d48dc2ce7eab29b063e38667417afce
17 Aug 2022 13:01:36.929open-balena-vpn-5cf5d597b-74wz5 vpn[714]: info: [vpn-127211.1] connection established with client_id=1600626 uuid=3d48dc2ce7eab29b063e38667417afce
`

**Comment by bernhardkaindl** [comment]
On July 1st, PR #263 replaced the previously used distinct OpenVPN connect and disconnect scripts with the OpenVPN Client Connect/Disconnect Script Plugin https://github.com/balena-io-modules/connect-disconnect-script-openvpn.

Since it, the plugin calls the script `openvpn/scripts/client-connect-disconnect.sh` "in the background" without waiting for the termination of each, which is the purpose PR #263.

But, when a client  connect and a client disconnect happen in quick succession, this leads to disaster:

For example, when a client is multi-homed or it's network connection moves from one interface to another this can happen:

When the OpenVPN client looses connectivity to the OpenVPN server over the network connection it currently uses,
it detects this and issues the log `[vpn.<domain>] Inactivity timeout (--ping-restart), restarting`.

The restart then tries to reconnect and if that reconnect ends up using a different network, this is logged in the journal log of the vpn container immediately:
```py
[vpn-4.1] MULTI: new connection by client 'bed42c2f02fc446fae52fa594e36226d' will cause previous
active sessions by this client to be dropped.
Remember to use the --duplicate-cn option if you want multiple clients using the same certificate
or username to concurrently connect.
[vpn-4.1] MULTI_sva: pool returned IPv4=100.64.0.3, IPv6=(Not enabled)
[vpn-4.1] PLUGIN_CALL: POST /etc/openvpn/plugins/openvpn-plugin-connect-disconnect-script.so/PLUGIN_CLIENT_CONNECT status=0
```

Dropping the old connection is ok, since the old openvpn client is no longer running at this point. Then, some VPN infos are logged and after that, the openvpn-plugin-connect-disconnect-script.so runs the `openvpn/scripts/client-connect-disconnect.sh` "in the background" concurrently, once with `bytes_received` set, and once not set.

The Instances of the script interpret `bytes_received` being not set as a connect event and sends a POST to the VPN_API_PORT.

When `bytes_received` is set, it sends a DELETE to the VPN_API_PORT.

Often, the order is reversted,
 "DELETE /api/v2/1/clients HTTP/1.1" 200 - "-" "curl/7.74.0"

nobody[1908]: openbalena-vpn connect - POST (these are logger calls which I added to the script for tracing)
nobody[1909]: openbalena-vpn disconnect - DELETE
vpn[1474]: ::ffff:127.0.0.1 - - [31/Aug/2022:08:11:17 +0000] "POST /api/v2/1/clients HTTP/1.1" 200 - "-" "curl/7.74.0"
vpn[1474]: ::ffff:127.0.0.1 - - [31/Aug/2022:08:11:16 +0000] "DELETE /api/v2/1/clients HTTP/1.1" 200 - "-" "curl/7.74.0"

This results in the device being listed as offline when in openvpn it is in fact online.

**Comment by kb2ma** [comment]
Thanks for the report, Bernhard.

@Page- , @PranavPeshwe

**Comment by bernhardkaindl** [comment]
@kb2ma Thanks for notifing @Page- and @PranavPeshwe!

The summary of the issue which I see (yours might be different, but could be the same), is:

Due to e.g. network interruptions or a hardware/power-on reset of a BalenaOS device, the openvpn server can end up receiving a new connection from a openvpn client from which it believes that it still has a connection with.

That existing connection could be from a no longer used, previous network connection or from the old boot of the BalenaOS device for example.

The OpenVPN server then replaces the old connection with the new connection, issues a client-disconnect event for the old connection and a client-connect event for the new connection, and both events happen at the same time.

If the device is unlucky, the client-connect event could get sent thru `curl -X POST` to the API before the client-disconnect event thru `curl -X DELETE`.

Of course, the precondition for this is that the server still believes that it has an old connection which it has to disconnect, when the reconnect happens.

A simple solution would be to not make the curl -X POST calls increment a connection counter and the curl -X DELETE calls decrement this counter. The device would only be marked offline when this counter returns to 0.

**Comment by Page-** [comment]
@bernhardkaindl this is an amazing dive into precisely what's happening and does match my understanding completely. As for the solution a refcount makes a lot of sense and could take over from the existing mechanism that's in place to prevent against out of sync disconnects which only handles the case of reconnecting to a different openvpn process

**Comment by kb2ma** [comment]
@bernhardkaindl , please let us know your experience on #295 . Your effort is what makes open source work. Vielen dank!
